local M = {}

-- Color palette (from minimal)
M.colors = {
	fg = "#DFE0EA",
	bg = "#191B20",
	none = "#191B20",
	dark = "#16181D",
	comment = "#4D5264",
	popup_back = "#515761",
	cursor_fg = "#DFE0EA",
	context = "#515761",
	cursor_bg = "#AEAFAD",
	accent = "#BBBBBB",
	diff_add = "#8CD881",
	diff_change = "#6CAEC0",
	cl_bg = "#707891",
	diff_text = "#568BB4",
	line_fg = "#555B6C",
	line_bg = "#1E2026",
	gutter_bg = "#1E2026",
	non_text = "#606978",
	selection_bg = "#5E697E",
	selection_fg = "#495163",
	vsplit_fg = "#cccccc",
	vsplit_bg = "#21252D",
	visual_select_bg = "#272932",

	red_key_w = "#E85A84",
	red_err = "#D95555",
	green_func = "#94DD8E",
	green = "#94DD8E",
	blue_type = "#7EB7E6",
	black1 = "#272932",
	black = "#16181D",
	white1 = "#CFD0D7",
	white = "#DFE0EA",
	gray_punc = "#515669",
	gray2 = "#6E7380",
	gray1 = "#343842",
	gray = "#21252D",
	orange = "#E0828D",
	orange_wr = "#E39A65",
	pink = "#D895C7",
	yellow = "#E9D26C",
}

-- Configuration options
M.config = {
	italic_comments = "italic",
	italic_keywords = "italic",
	italic_booleans = "italic",
	italic_functions = false,
	italic_variables = false,
	transparent_background = false,
}

function M.setup(opts)
	opts = opts or {}

	-- Merge config options
	M.config = vim.tbl_deep_extend("force", M.config, opts)

	local colors = M.colors
	local config = M.config

	-- Set vim options
	vim.o.termguicolors = true
	if vim.g.colors_name then
		vim.cmd("hi clear")
	end
	vim.o.background = "dark"

	local highlights = {
		-----------------------------------------
		--        Styles
		-----------------------------------------
		Bold = { bold = true },
		Italic = { italic = true },
		Underlined = { underline = true },

		-----------------------------------------
		--        Editor settings
		-----------------------------------------
		Boolean = { fg = colors.orange, italic = config.italic_booleans == "italic" },

		Character = { fg = colors.yellow },
		ColorColumn = { bg = colors.black1 },
		Comment = { fg = colors.comment, italic = config.italic_comments == "italic" },
		Conceal = { fg = colors.fg },
		Conditional = { fg = colors.red_key_w },
		Constant = { fg = colors.pink },
		Cursor = { fg = colors.yellow, bg = colors.bg },
		CursorColumn = { fg = "NONE", bg = "NONE" },
		CursorLine = { bg = colors.black1 },
		CursorLineNr = { fg = colors.white, bg = colors.gutter_bg, bold = true },

		Debug = { fg = colors.fg },
		Define = { fg = colors.blue_type },
		Delimiter = { fg = colors.gray_punc },
		DiffAdd = { fg = colors.green_func },
		DiffAdded = { fg = colors.green_func },
		DiffChange = { fg = colors.green_func },
		DiffDelete = { fg = colors.red_key_w },
		DiffRemoved = { fg = colors.red_key_w },
		DiffText = { fg = colors.white1 },
		DiffFile = { fg = colors.pink },

		Error = { fg = colors.red_key_w, bg = colors.bg, bold = true },
		ErrorMsg = { fg = colors.gray, bg = colors.red_err, bold = true },
		Exception = { fg = colors.white },

		Float = { fg = colors.orange },
		FloatBorder = { fg = colors.gray2, bg = "NONE" },
		FoldColumn = { fg = colors.line_fg },
		Folded = { fg = colors.white, bg = colors.gray },
		Function = { fg = colors.green_func },

		Identifier = { fg = colors.white1 },
		Ignore = { fg = colors.gray_punc },
		IncSearch = { fg = colors.bg, bg = colors.orange },
		Include = { fg = colors.blue_type, italic = config.italic_keywords == "italic" },

		Keyword = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },

		Label = { fg = colors.red_key_w },
		LineNr = { fg = colors.line_fg, bg = colors.line_bg },

		Macro = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },
		MatchParen = { fg = colors.white1, bg = colors.black },
		MatchParenCur = { underline = true },
		MatchWord = { underline = true },
		MatchWordCur = { underline = true },
		ModeMsg = { fg = colors.fg, bg = colors.bg },
		MoreMsg = { fg = colors.orange_wr },
		MsgArea = { fg = colors.fg, bg = config.transparent_background and "NONE" or colors.bg },
		MsgSeparator = { fg = colors.fg, bg = colors.bg },

		NonText = { fg = colors.gray2 },
		Normal = { fg = colors.fg, bg = config.transparent_background and "NONE" or colors.bg },
		NormalFloat = { bg = colors.dark },
		NormalNC = { fg = colors.white, bg = config.transparent_background and "NONE" or colors.bg },
		Number = { fg = colors.orange },

		Operator = { fg = colors.white },
		Pmenu = { fg = colors.white1, bg = colors.black },
		PmenuSbar = { bg = colors.gray },
		PmenuSel = { fg = colors.line_fg, bg = colors.black },
		PmenuThumb = { bg = colors.black },
		PreCondit = { fg = colors.blue_type },
		PreProc = { fg = colors.blue_type },

		Question = { fg = colors.green_func },
		QuickFixLine = { fg = colors.orange_wr },

		Repeat = { fg = colors.red_key_w },

		Search = { fg = colors.line_fg, bg = colors.orange },
		SignColumn = { bg = colors.line_bg },
		Special = { fg = colors.gray_punc },
		SpecialChar = { fg = colors.yellow },
		SpecialComment = { fg = colors.pink },
		SpecialKey = { fg = colors.gray_punc, bold = true },
		SpellBad = { fg = colors.red_key_w, underline = true },
		SpellCap = { fg = colors.orange, underline = true },
		SpellLocal = { fg = colors.green, underline = true },
		SpellRare = { fg = colors.pink, underline = true },
		Statement = { fg = colors.red_key_w },
		StatusLine = { fg = colors.line_fg, bg = colors.black },
		StatusLineNC = { fg = colors.line_fg, bg = colors.black },
		StatusLineSeparator = { fg = colors.dark },
		StatusLineTerm = { fg = colors.green_func, bg = colors.black },
		StatusLineTermNC = { fg = colors.gray_punc, bg = colors.black },
		StorageClass = { fg = colors.red_key_w },
		String = { fg = colors.yellow },
		Structure = { fg = colors.green_func },
		Substitute = { fg = colors.gray2, bg = colors.orange },

		TabLine = { fg = colors.line_fg },
		TabLineFill = { fg = colors.line_fg },
		TabLineSel = { fg = colors.fg },
		Tag = { fg = colors.gray_punc },
		TermCursor = { fg = colors.cursor_fg, bg = colors.cursor_bg },
		TermCursorNC = { fg = colors.cursor_fg, bg = colors.cursor_bg },
		Title = { fg = colors.gray_punc },
		Todo = { fg = colors.yellow, bold = true },
		Type = { fg = colors.blue_type, italic = config.italic_keywords == "italic" },
		Typedef = { fg = colors.blue_type, italic = config.italic_keywords == "italic" },

		Variable = { fg = colors.white },
		VertSplit = { fg = colors.vsplit_bg },
		Visual = { fg = "NONE", bg = colors.visual_select_bg, bold = true },
		VisualNOS = { fg = colors.selection_fg, bg = colors.selection_bg },

		WarningMsg = { fg = colors.orange_wr, bg = colors.none },
		Whitespace = { fg = colors.non_text },
		WildMenu = { fg = colors.fg },
		lCursor = { fg = colors.cursor_fg, bg = colors.cursor_bg },

		-- Markdown
		markdownBold = { fg = colors.white, bold = true },
		markdownCode = { fg = colors.orange },
		markdownCodeBlock = { fg = colors.orange },
		markdownUrl = { fg = colors.pink, underline = true },
		markdownCodeError = { fg = colors.red_err },
		markdownH1 = { fg = colors.white },
		markdownH2 = { fg = colors.white },
		markdownH3 = { fg = colors.white },
		markdownH4 = { fg = colors.white },
		markdownH5 = { fg = colors.white },
		markdownH6 = { fg = colors.white },
		markdownId = { fg = colors.pink },
		markdownItalic = { fg = colors.white, italic = true },
		markdownLinkText = { fg = colors.white },
		markdownRule = { fg = colors.accent },
		markdownListMarker = { fg = colors.red_key_w },
		markdownHeadingDelimiter = { fg = colors.white },
		markdownHeadingRule = { fg = colors.accent },
		markdownUrlTitleDelimiter = { fg = colors.white },
		markdownCodeSpecial = { fg = colors.orange },
		markdownCodeDelimiter = { fg = colors.green },
		markdownBlockquote = { fg = colors.accent },
		markdownIdDeclaration = { fg = colors.white },
		markdownIdDelimiter = { fg = colors.gray2 },
		markdownLinkDelimiter = { fg = colors.gray2 },
		markdownOrderedListMarker = { fg = colors.red_key_w },

		-----------------------------------------
		--   Plugin support
		-----------------------------------------

		-- Buffer
		BufferCurrent = { fg = colors.fg, bg = colors.gray },
		BufferCurrentIndex = { fg = colors.fg, bg = colors.bg },
		BufferCurrentMod = { fg = colors.yellow, bg = colors.bg },
		BufferCurrentSign = { fg = colors.blue_type, bg = colors.bg },
		BufferCurrentTarget = { fg = colors.red_key_w, bg = colors.bg, bold = true },
		BufferInactive = { fg = colors.gray2, bg = colors.dark },
		BufferInactiveIndex = { fg = colors.gray2, bg = colors.dark },
		BufferInactiveMod = { fg = colors.yellow, bg = colors.dark },
		BufferInactiveSign = { fg = colors.gray2, bg = colors.dark },
		BufferInactiveTarget = { fg = colors.red_key_w, bg = colors.dark, bold = true },
		BufferVisible = { fg = colors.fg, bg = colors.bg },
		BufferVisibleIndex = { fg = colors.fg, bg = colors.bg },
		BufferVisibleMod = { fg = colors.yellow, bg = colors.bg },
		BufferVisibleSign = { fg = colors.green, bg = colors.bg },
		BufferVisibleTarget = { fg = colors.red_key_w, bg = colors.bg, bold = true },
		BufferLineFill = { fg = colors.fg, bg = "NONE", bold = true },

		-- WhichKey
		WhichKey = { fg = colors.blue_type },
		WhichKeySeperator = { fg = colors.red_key_w },
		WhichKeyGroup = { fg = colors.pink },
		WhichKeyDesc = { fg = colors.white },
		WhichKeyFloat = { bg = colors.dark },

		-- Cmp
		CmpItemAbbrDeprecated = { fg = colors.comment },
		CmpDocumentation = { fg = colors.fg },
		CmpDocumentationBorder = { fg = colors.gray2 },
		CmpItemAbbr = { fg = colors.fg },
		CmpItemAbbrMatch = { fg = colors.blue_type },
		CmpItemAbbrMatchFuzzy = { fg = colors.blue_type },
		CmpItemKind = { fg = colors.green_func },
		CmpItemKindMethod = { fg = colors.blue_type },
		CmpItemKindConstructor = { fg = colors.yellow },
		CmpItemKindClass = { fg = colors.red_key_w },
		CmpItemKindVariable = { fg = colors.white },
		CmpItemKindField = { fg = colors.white },
		CmpItemKindProperty = { fg = colors.white },
		CmpItemKindEnumMember = { fg = colors.orange },
		CmpItemKindConstant = { fg = colors.orange },
		CmpItemKindEnum = { fg = colors.blue_type },
		CmpItemKindStruct = { fg = colors.blue_type },
		CmpItemKindKeyword = { fg = colors.pink },
		CmpItemMenu = { fg = colors.pink },
		CmpItemKindOperator = { fg = colors.red_key_w },

		-- Dashboard
		DashboardCenter = { fg = colors.white },
		DashboardFooter = { fg = colors.yellow },
		DashboardHeader = { fg = colors.green_func },

		-- Debug
		debugBreakpoint = { fg = colors.red_key_w, reverse = true },
		debugPc = { bg = colors.white1 },

		-- Diffview
		DiffViewNormal = { fg = colors.gray2, bg = colors.dark },
		DiffviewFilePanelDeletion = { fg = colors.red_err },
		DiffviewFilePanelInsertion = { fg = colors.diff_add },
		DiffviewStatusAdded = { fg = colors.diff_add },
		DiffviewStatusDeleted = { fg = colors.red_err },
		DiffviewStatusModified = { fg = colors.diff_change },
		DiffviewStatusRenamed = { fg = colors.diff_change },
		DiffviewVertSplit = { bg = colors.bg },

		-- Gitsigns
		GitSignsAdd = { fg = colors.green_func, bg = colors.line_bg },
		GitSignsChange = { fg = colors.diff_change, bg = colors.line_bg },
		GitSignsDelete = { fg = colors.red_key_w, bg = colors.line_bg },

		-- GitGutter
		GitGutterAdd = { fg = colors.diff_add },
		GitGutterChange = { fg = colors.diff_change },
		GitGutterDelete = { fg = colors.red_err },

		-- Indent-blankline
		IndentBlanklineChar = { fg = colors.black1 },
		IndentBlanklineContextChar = { fg = colors.gray2 },
		IndentBlanklineSpaceChar = { fg = colors.white1 },
		IndentBlanklineSpaceCharBlankline = { fg = colors.yellow },

		-- LSP Diagnostics
		DiagnosticVirtualTextInfo = { fg = colors.yellow },
		DiagnosticHint = { fg = colors.blue_type },
		DiagnosticError = { fg = colors.red_err },
		DiagnosticInfo = { fg = colors.yellow },
		DiagnosticVirtualTextWarn = { fg = colors.orange_wr },
		DiagnosticWarn = { fg = colors.orange_wr },

		DiagnosticFloatingError = { fg = colors.red_err },
		DiagnosticFloatingHint = { fg = colors.blue_type },
		DiagnosticFloatingInfo = { fg = colors.yellow },
		DiagnosticFloatingWarn = { fg = colors.orange_wr },

		DiagnosticSignError = { fg = colors.red_err, bg = colors.line_bg },
		DiagnosticSignHint = { fg = colors.blue_type, bg = colors.line_bg },
		DiagnosticSignInfo = { fg = colors.yellow, bg = colors.line_bg },
		DiagnosticSignWarn = { fg = colors.orange_wr, bg = colors.line_bg },

		DiagnosticUnderlineError = { underline = true },
		DiagnosticUnderlineHint = { underline = true },
		DiagnosticUnderlineInfo = { underline = true },
		DiagnosticUnderlineWarn = { underline = true },

		DiagnosticVirtualTextError = { fg = colors.red_err },
		DiagnosticVirtualTextHint = { fg = colors.gray2 },

		-- NERDTree
		Directory = { fg = colors.white },
		NERDTreeUp = { fg = colors.yellow },
		NERDTreeDir = { fg = colors.blue_type },
		NERDTreeOpenable = { fg = colors.comment },
		NERDTreeClosable = { fg = colors.red_key_w },
		NERDTreeIgnore = { fg = colors.comment },
		NERDTreeHelpKey = { fg = colors.white },
		NERDTreeHelpTitle = { fg = colors.pink },
		NERDTreeToggleOn = { fg = colors.green_func },
		NERDTreeToggleOff = { fg = colors.orange },
		NERDTreeHelpCommand = { fg = colors.yellow },
		NERDTreeFile = { fg = colors.white },
		NERDTreeLinkTarget = { fg = colors.blue_type },
		NERDTreeLinkFile = { fg = colors.green_func },
		NERDTreeLinkDir = { fg = colors.pink },
		NERDTreeNodeDelimiters = { fg = colors.comment },
		NERDTreeDirSlash = { fg = colors.comment },
		NERDTreeExecFile = { fg = colors.green_func },
		NERDTreeRO = { fg = colors.orange },
		NERDTreeBookmarkName = { fg = colors.orange },
		NERDTreeFlags = { fg = colors.red_key_w },
		NERDTreeCWD = { fg = colors.red_key_w },
		NERDTreeBookmarksLeader = { fg = colors.blue_type },
		NERDTreeBookmarksHeader = { fg = colors.red_key_w },
		NERDTreeBookmark = { fg = colors.orange },
		NERDTreePart = { fg = colors.orange },
		NERDTreePartFile = { fg = colors.blue_type },
		NERDTreeCurrentNode = { fg = colors.comment },

		-- Startify
		StartifyEndOfBuffer = { fg = colors.non_text },
		StartifyNumber = { fg = colors.red_key_w },
		StartifySelect = { fg = colors.comment },
		StartifyBracket = { fg = colors.white },
		StartifySpecial = { fg = colors.yellow },
		StartifyVar = { fg = colors.comment },
		StartifyPath = { fg = colors.comment },
		StartifyFile = { fg = colors.blue_type },
		StartifySlash = { fg = colors.comment },
		StartifyHeader = { fg = colors.blue_type },
		StartifyFooter = { fg = colors.pink },
		StartifySection = { fg = colors.pink },

		-- Indent Guides
		IndentGuidesEven = { fg = colors.white1 },
		IndentGuidesOdd = { fg = colors.comment },

		-- Flutter Tools
		FlutterWidgetGuides = { fg = colors.gray2 },

		-- Python
		pythonConditional = { fg = colors.red_key_w },
		pythonException = { fg = colors.pink },
		pythonFunction = { fg = colors.green_func },
		pythonInclude = { fg = colors.red_key_w },
		pythonOperator = { fg = colors.red_key_w },
		pythonStatement = { fg = colors.white },
		pythonBoolean = { fg = colors.white },

		-- Neogit
		NeogitBranch = { fg = colors.pink },
		NeogitRemote = { fg = colors.pink },
		NeogitHunkHeader = { fg = colors.accent, bg = colors.dark },
		NeogitDiffContext = { fg = colors.accent, bg = colors.bg },
		NeogitDiffAdd = { fg = colors.diff_add, bg = colors.dark },
		NeogitDiffDelete = { fg = colors.red_err, bg = colors.dark },
		NeogitHunkHeaderHighlight = { fg = colors.accent, bg = colors.dark },
		NeogitDiffContextHighlight = { fg = colors.accent, bg = colors.bg },
		NeogitDiffAddHighlight = { fg = colors.diff_add, bg = colors.dark },
		NeogitDiffDeleteHighlight = { fg = colors.red_err, bg = colors.dark },

		-- Nvim-tree
		NvimTreeFolderIcon = { fg = colors.orange },
		NvimTreeEmptyFolderName = { fg = colors.yellow, italic = true },
		NvimTreeCursorLine = { fg = colors.line_fg, bg = colors.black1 },
		NvimTreeExecFile = { fg = colors.green },
		NvimTreeFolderName = { fg = colors.white1 },
		NvimTreeGitDeleted = { fg = colors.red_err },
		NvimTreeGitDirty = { fg = colors.diff_add },
		NvimTreeGitMerge = { fg = colors.diff_change },
		NvimTreeGitNew = { fg = colors.diff_add },
		NvimTreeGitRenamed = { fg = colors.diff_change },
		NvimTreeGitStaged = { fg = colors.diff_add },
		NvimTreeImageFile = { fg = colors.pink },
		NvimTreeIndentMarker = { fg = colors.comment },
		NvimTreeNormal = { fg = colors.white1, bg = colors.black },
		NvimTreeNormalNC = { bg = colors.black },
		NvimTreeOpenedFolderName = { fg = colors.white1, italic = true },
		NvimTreeRootFolder = { fg = colors.yellow, bold = true },
		NvimTreeSpecialFile = { fg = colors.orange },
		NvimTreeSymlink = { fg = colors.yellow },
		NvimTreeVertSplit = { fg = colors.black },
		NvimTreeEndOfBuffer = { fg = colors.non_text },

		-- Telescope
		TelescopeBorder = { fg = colors.white, bg = config.transparent_background and "NONE" or colors.bg },
		TelescopeMatching = { fg = colors.yellow },
		TelescopePromptPrefix = { fg = colors.green_func },
		TelescopeSelection = { fg = colors.comment, bg = colors.black1 },

		-- Trouble
		TroubleTextInformation = { fg = colors.blue_type },
		TroubleFile = { fg = colors.yellow },
		TroubleFoldIcon = { fg = colors.blue_type },
		TroubleCount = { fg = colors.red_key_w },
		TroubleError = { fg = colors.red_key_w, bg = colors.line_fg },
		TroubleTextError = { fg = colors.red_key_w },
		TroubleNormal = { fg = colors.white },
		TroubleLocation = { fg = colors.white },
		TroubleIndent = { fg = colors.comment },
		TroubleCode = { fg = colors.orange_wr },
		TroubleSignError = { fg = colors.red_key_w },
		TroubleSignWarning = { fg = colors.orange_wr },
		TroubleWarning = { fg = colors.orange_wr },
		TroublePreview = { fg = colors.red_key_w },
		TroubleSignInformation = { fg = colors.white },
		TroubleSource = { fg = colors.blue_type },
		TroubleSignHint = { fg = colors.green },
		TroubleSignOther = { fg = colors.green },
		TroubleTextWarning = { fg = colors.orange_wr },
		TroubleInformation = { fg = colors.white },
		TroubleHint = { fg = colors.orange_wr },
		TroubleTextHint = { fg = colors.white },
		TroubleText = { fg = colors.white },

		-- CodeActionMenu
		CodeActionMenuWarningMessageText = { fg = colors.orange_wr },
		CodeActionMenuWarningMessageBorder = { fg = colors.red_key_w },
		CodeActionMenuMenuIndex = { fg = colors.blue_type },
		CodeActionMenuMenuKind = { fg = colors.green },
		CodeActionMenuMenuTitle = { fg = colors.white },
		CodeActionMenuMenuDisabled = { fg = colors.comment },
		CodeActionMenuMenuSelection = { fg = colors.blue_type },
		CodeActionMenuDetailsTitle = { fg = colors.white },
		CodeActionMenuDetailsLabel = { fg = colors.yellow },
		CodeActionMenuDetailsPreferred = { fg = colors.green },
		CodeActionMenuDetailsDisabled = { fg = colors.comment },
		CodeActionMenuDetailsUndefined = { fg = colors.comment },

		-- CMake
		cmakeCommand = { fg = colors.white },
		cmakeArguments = { fg = colors.white },
		cmakeKWvariable_watch = { fg = colors.white },
		cmakeKWproject = { fg = colors.pink },
		cmakeGeneratorExpressions = { fg = colors.pink },
		cmakeVariable = { fg = colors.white },
		cmakeKWuse_mangled_mesa = { fg = colors.fg, italic = true },

		-- TreeSitter
		TSAnnotation = { fg = colors.yellow },
		TSAttribute = { fg = colors.white },
		TSBoolean = { fg = colors.orange, italic = config.italic_booleans == "italic" },
		TSCharacter = { fg = colors.yellow },
		TSCharacterSpecial = { fg = colors.yellow },
		TSComment = { fg = colors.comment, italic = config.italic_comments == "italic" },
		TSConditional = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },
		TSConstBuiltin = { fg = colors.pink },
		TSConstMacro = { fg = colors.blue_type },
		TSConstant = { fg = colors.pink },
		TSConstructor = { fg = colors.white },
		TSEmphasis = { italic = true },
		TSError = { fg = colors.red_err, bg = colors.bg, bold = true },
		TSException = { fg = colors.red_key_w },
		TSField = { fg = colors.white },
		TSFloat = { fg = colors.orange },
		TSFuncBuiltin = { fg = colors.green_func, italic = config.italic_functions },
		TSFuncMacro = { fg = colors.blue_type, italic = config.italic_functions },
		TSFunction = { fg = colors.green_func, italic = config.italic_functions },
		TSInclude = { fg = colors.red_key_w },
		TSKeyword = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },
		TSKeywordFunction = { fg = colors.red_key_w, italic = config.italic_functions },
		TSKeywordOperator = { fg = colors.red_key_w },
		TSKeywordReturn = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },
		TSNone = { fg = colors.orange },
		TSLabel = { fg = colors.pink },
		TSLiteral = { fg = colors.yellow },
		TSMethod = { fg = colors.green_func, italic = config.italic_functions },
		TSNamespace = { fg = colors.blue_type },
		TSNumber = { fg = colors.orange },
		TSOperator = { fg = colors.red_key_w },
		TSParameter = { fg = colors.white },
		TSParameterReference = { fg = colors.white },
		TSProperty = { fg = colors.white },
		TSPunctBracket = { fg = colors.white },
		TSPunctDelimiter = { fg = colors.white },
		TSPunctSpecial = { fg = colors.gray_punc },
		TSQueryLinterError = { fg = colors.red_err },
		TSRepeat = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },
		TSString = { fg = colors.yellow },
		TSStringEscape = { fg = colors.green },
		TSStringRegex = { fg = colors.yellow },
		TSStrong = { fg = colors.yellow },
		TSStructure = { fg = colors.red_key_w },
		TSSymbol = { fg = colors.white },
		TSTag = { fg = colors.red_key_w },
		TSTagDelimiter = { fg = colors.gray_punc },
		TSText = { fg = colors.fg },
		TSTitle = { fg = colors.white, bold = true },
		TSType = { fg = colors.blue_type },
		TSTypeBuiltin = { fg = colors.blue_type },
		TSTodo = { fg = colors.orange },
		TSTypeQualifier = { fg = colors.red_key_w },
		TSURI = { fg = colors.yellow, underline = true },
		TSUnderline = { underline = true },
		TSVariable = { fg = colors.white, italic = config.italic_variables },
		TSVariableBuiltin = { fg = colors.pink, italic = config.italic_variables },
		TSDefine = { fg = colors.red_key_w },

		-- Modern TreeSitter groups (@-prefixed)
		["@annotation"] = { fg = colors.yellow },
		["@attribute"] = { fg = colors.white },
		["@boolean"] = { fg = colors.orange, italic = config.italic_booleans == "italic" },
		["@character"] = { fg = colors.yellow },
		["@character.special"] = { fg = colors.yellow },
		["@comment"] = { fg = colors.comment, italic = config.italic_comments == "italic" },
		["@conditional"] = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },
		["@constant"] = { fg = colors.pink },
		["@constant.builtin"] = { fg = colors.pink },
		["@constant.macro"] = { fg = colors.blue_type },
		["@constructor"] = { fg = colors.white },
		["@emphasis"] = { italic = true },
		["@error"] = { fg = colors.red_err, bg = colors.bg, bold = true },
		["@exception"] = { fg = colors.red_key_w },
		["@field"] = { fg = colors.white },
		["@float"] = { fg = colors.orange },
		["@function"] = { fg = colors.green_func, italic = config.italic_functions },
		["@function.builtin"] = { fg = colors.green_func, italic = config.italic_functions },
		["@function.macro"] = { fg = colors.blue_type, italic = config.italic_functions },
		["@include"] = { fg = colors.red_key_w },
		["@keyword"] = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },
		["@keyword.function"] = { fg = colors.red_key_w, italic = config.italic_functions },
		["@keyword.operator"] = { fg = colors.red_key_w },
		["@keyword.return"] = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },
		["@label"] = { fg = colors.pink },
		["@method"] = { fg = colors.green_func, italic = config.italic_functions },
		["@namespace"] = { fg = colors.blue_type },
		["@none"] = { fg = colors.orange },
		["@number"] = { fg = colors.orange },
		["@operator"] = { fg = colors.red_key_w },
		["@parameter"] = { fg = colors.white },
		["@parameter.reference"] = { fg = colors.white },
		["@property"] = { fg = colors.white },
		["@punctuation.bracket"] = { fg = colors.white },
		["@punctuation.delimiter"] = { fg = colors.white },
		["@punctuation.special"] = { fg = colors.gray_punc },
		["@repeat"] = { fg = colors.red_key_w, italic = config.italic_keywords == "italic" },
		["@string"] = { fg = colors.green },
		["@string.escape"] = { fg = colors.green },
		["@string.regex"] = { fg = colors.yellow },
		["@string.special"] = { fg = colors.yellow },
		["@symbol"] = { fg = colors.white },
		["@tag"] = { fg = colors.red_key_w },
		["@tag.delimiter"] = { fg = colors.gray_punc },
		["@text"] = { fg = colors.fg },
		["@text.strong"] = { fg = colors.yellow },
		["@text.title"] = { fg = colors.white, bold = true },
		["@text.uri"] = { fg = colors.yellow, underline = true },
		["@text.underline"] = { underline = true },
		["@type"] = { fg = colors.blue_type },
		["@type.builtin"] = { fg = colors.blue_type },
		["@type.qualifier"] = { fg = colors.red_key_w },
		["@variable"] = { fg = colors.white, italic = config.italic_variables },
		["@variable.builtin"] = { fg = colors.pink, italic = config.italic_variables },
	}

	-- Apply on_highlights callback if provided
	if opts.on_highlights and type(opts.on_highlights) == "function" then
		opts.on_highlights(highlights, colors)
	end

	-- Apply all highlights
	for group, hl_opts in pairs(highlights) do
		vim.api.nvim_set_hl(0, group, hl_opts)
	end
end

return M
